### ISSUE TITLE
minecraft server considered crashed by watchdog (AllowSuspend=true)

### ISSUE THREAD

**Issue by gekigek99** [gekware/minecraft-server-hibernation#147]
### Current Behavior (🐛 Bug)

minecraft server considered crashed by watch dog when process is unsuspended. (don't know if it's just a log or it implies some unexpected behaviour from ms)

### Expected Behavior

just log that the server is overloaded and running way behind with ticks.

### Steps to Reproduce

set AllowSuspend to true, let the server be frozen and then unsuspend it.

It might not happen all the time: probably only happenss when the server is frozen and forceful freeze is sent (with stop command).

possible solution is setting/checking for `max-tick-time=-1` in `server.properties` (when AllowSuspend is set to true)

### MSH Logs

![server crashed when unsuspending](https://user-images.githubusercontent.com/53654579/164120381-670345c4-75ba-4833-b162-1531afa55cb0.jpeg)

### MSH-Version

2.4.6

### Operating system

linux

### Minecraft Version

1.18.2

### Minecraft Server Software

vanilla

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
this problem was already referenced by @Br31zh in [this comment](https://github.com/gekware/minecraft-server-hibernation/issues/51#issue-733754549) of issue #51

**Comment by gekigek99** [comment]
log of server:
- paper server
- 4 min of process tree suspension
- max-tick-time=-1

https://zerobin.net/?4c6868fac51321c1#kS2e6zQ5AZPS89EHNox/+5WKQTwmMbZlMsYm0jjkW3k=

**Comment by gekigek99** [comment]
@Br31zh does it happen also to you? how do you prevent that?

**Comment by gekigek99** [comment]
setting `timeout-time: -1` in `spigot.yml` prevents the ms shutdown/restart

[log of server](https://zerobin.net/?ed903844c6329803#3XcfhqI08gdoUEPwDA1uIcAheFxOloE4Etozs2wn1LY=):
- paper server 
- 3 min of process tree suspension
- server.properties -> max-tick-time=-1
- spigot.yml -> timeout-time: -1

**Comment by Br31zh** [comment]
I’m using a fabric server, not a spigot or paper one. So server.properties -> max-tick-time=-1 is a sufficient configuration to prevent it crashing (it’s the same for a vanilla server).

Here is my log with my own system, and my fabric server: https://haste.breizh.pm/buzodigoru.txt (and you can see that it keep suspend / resume a bit too much, that’s why I call it shaky).

So I can’t help you here, sorry.

**Comment by gekigek99** [comment]
Ah ok thanks anyway for that info!

I think that all that `Can't keep up! Is the server overloaded?` it's fine and inevitable... If the players can play it's good

**Comment by gekigek99** [comment]
setting `restart-on-crash: false` in spigot.yml prevents the ms shutdown/restart

[log of server](https://hastebin.skyra.pw/uvutikaquh.yaml):

- paper server
- 2 min of process tree suspension
- server.properties -> max-tick-time=-1
- spigot.yml -> timeout-time: -1
- spigot.yml -> restart-on-crash: false

this seems to solve it (there is still the crash report but the player is able to instantly join the server)

**Comment by Br31zh** [comment]
Yeah, totally, the Can't keep up! Is the server overloaded? is just there to say that the last tick was too long (of course since the process was frozen). 

Here is the log when a player join the game: https://haste.breizh.pm/aloyosukil.txt

So yeah, if the server work flawlessly after resuming, even with some warnings in the logs, it’s ok.

**Comment by gekigek99** [comment]
what is the longest time the server can be suspended without crashing when restarting?
because i tryed resuming it after 20h but it crashed i think.

**Comment by Br31zh** [comment]
It never crashed here, even after more than 24h (in 1.16, before I change the way I’m suspending it). I just had the Can’t keep up message. If it’s still with paper / spigot, then maybe that’s the problem.

But I don’t have these timing often, since it’s on my personal computer (I shutdown or reboot it manually almost every day).

**Comment by NukaExpress** [comment]
My server keeps crashing even though I changed the following settings:

- paper server (1.19)
- 5 min of process tree suspension
- server.properties -> max-tick-time=-1
- spigot.yml -> timeout-time: -1
- spigot.yml -> restart-on-crash: false
- bukkit.yml -> warn-on-overload: false
- paper-global.yml -> early-warning-delay: -1
- paper-global.yml ->early-warning-every: -1

Here is the [paper-log](https://zerobin.net/?1ddf6e9f74d03bca#almoVuXHwFOtxCE2DgIBjSPN3i85pT9R2ubdhVbQuK4=)

I guess it's because of the 1.19.
The Hibernate plugin also no longer works.

**Comment by gekigek99** [comment]
planning to solve it with a sort of _"suspension refresh function"_ that the user can set.

_not ideal, but playing with single threads and watchdogs its pretty tricky..._

reminder: add a start flag for this new config parameter

**Comment by gekigek99** [comment]
fixed in 5fcf9b80bc333e90bb4b37d17957944b90bc365f

this is not the "golden" solution but does the job while keeping resources usage to a reasonably low amount

@Br31zh @MarkBremer can you test it?
