### ISSUE TITLE
Possibly work with server panels. 

### ISSUE THREAD

**Issue by hobojoe551** [gekware/minecraft-server-hibernation#42]
I feel like this could be really useful for server panels that don't support this feature. The main one I can think of is Crafty Controller. Its a very barebones panel, but it is missing a hibernation feature.

**Comment by gekigek99** [comment]
ok it could be interesting... can you specify a little more what do you have in mind?

**Comment by lubocode** [comment]
They probably meant, we should contact the devs from other open source projects e.g. [https://craftycontrol.com/](https://craftycontrol.com/) and work together to add the start stop functionality to their system.

Since we have to finish with what we planned first and then probably do some optimizing/cleaning, this is a thing for next year in the earliest.

**Comment by hobojoe551** [comment]
Sorry didn't even see the replies until just now. That is basically what I meant, and I didn't expect you to even consider it, and even then I didn't expect you guys to be able to even do it anytime soon.

**Comment by gekigek99** [comment]
@hobojoe551 this is an egg for minecarft servers that implements msh in it:

https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg

Test it and if you like that project give it a star on github!
